######################## default configuration ####################
baseURL = "https://coffshomelyhomeservices.com/site/"
title = "Homely"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about/"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 4

# [[menu.main]]
# name = "Sample Page"
# URL = "sample-page/"
# weight = 5

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact/"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "Themefisher"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "The best pool care your pool can have."
image = "images/2020-landscape-1-2.png"


[params.services]
first = "we do lots of stuff"
first_img = "images/2020-landscape-1-2.png"
second = "we do lots of stuff"
second_img = "we do lots of stuff"
third = "we do lots of stuff"
third_img = "we do lots of stuff"
forth = "we do lots of stuff"
forth_img = "we do lots of stuff"

# blog
[params.blog]
heading = "The premier service provider of your pool."

# call to action
[params.call_to_action]
enable = true
title = "Contact us for more information."
content = ""
button_label = "Contact Us"
button_url = "contact/"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About This Site"
content = "We here at homely are your local pool service technicians. Our friendly and reliable staff always provide a professional and affordable service Coffs wide."
# address = "123 Main Street <br> New York, NY 10001"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday: 11:00AM–3:00PM"
copyright = "Copyright © Designed by Themefisher & Developed by Gethugothemes"

############################# social site ########################
[params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
# instagram = "#"
# email = "#"
# linkedin = "#"
