name = "Homely"
license = "GPL v2"
licenselink = "https://github.com/themefisher/homely/blob/master/LICENSE"
description = "Homely Home Services Cleaning Your Pool"
homepage = "https://gethugothemes.com/products/homely/"
tags = ['pool','maintenance', 'cleaning', 'home care', 'Coffs Harbour', 'Coffs']
features = ['responsive']
min_version = "0.62.2"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"